mapk
thesis20/Graph-Based-Recommender pull request #15
Opened 2020-11-10 10:31 UTC by Eduardsen

2020-11-10 10:41 UTC, Moesgaarda approved these changes

2020-11-13 08:36 UTC, andpaacoke requested changes

2020-11-13 08:36 UTC, andpaacoke commented on evaluation/mapk.py
> +    k_val: The number of items in each list of recommendations
Ved ikke om der også bør stå hvad typer det er? et dictionary kan jo være mange ting

2020-11-13 13:28 UTC, andpaacoke approved these changes

2020-11-16 09:47 UTC, merged