Modify a dataframe with a context feature that affects ratings
thesis20/Graph-Based-Recommender pull request #16
Opened 2020-11-11 13:21 UTC by andpaacoke

2020-11-13 08:33 UTC, Moesgaarda commented
Burde den her ikke ligge sammen med CAMF filerne? Det er vel ret specifikt der til

2020-11-13 08:39 UTC, andpaacoke commented
@Moesgaarda Det kan bruges til alle former for algoritmer der gør brug af context da det tilføjer en context variable som påvirker ratings enten negativt eller positivt afhængig af værdien af denne. Så item splitting ville også kunne gøre brug af det i guess

2020-11-16 14:26 UTC, Moesgaarda requested changes
Flyt den ind i dataloaders/transformation

2020-11-17 07:05 UTC, Moesgaarda approved these changes

2020-11-17 09:04 UTC, Eduardsen approved these changes

2020-11-17 09:08 UTC, merged